Created season class and tests
michalflis/JUnit-Params-Mockito pull request #4
Opened 2021-07-22 18:49 UTC by michalflis

2021-07-23 05:27 UTC, radoslawdabrowski commented on src/test/java/SeasonNameTest.java
> +
Unnecessary `new line`

2021-07-23 05:28 UTC, radoslawdabrowski commented on src/main/java/SeasonName.java
> +            default: throw new RuntimeException();
Zaimplementuj bardziej semantyczny Exception który będzie rozszerzać RuntimeException

2021-07-23 05:28 UTC, radoslawdabrowski requested changes
Poprawki

2021-07-25 18:30 UTC, michalflis commented on src/main/java/SeasonName.java
> +            default: throw new RuntimeException();
Czy IllegalArgumentException  bedzie tutuaj ok?

2021-07-25 20:08 UTC, mtszpater approved these changes

2021-07-27 17:36 UTC, merged