Created my own list
michalflis/JUnit-Params-Mockito pull request #9
Opened 2021-07-27 21:36 UTC by michalflis

2021-07-29 06:57 UTC, mtszpater commented on src/main/java/javacollections/OwnList.java
> +    Integer get(int i);
jakieś testy? ;)

2021-07-29 15:39 UTC, michalflis commented on src/main/java/javacollections/OwnList.java
> +    Integer get(int i);
Rozumiem że chodzi o testy do metod, nie do tego konkretnego kawałka kodu?

2021-07-29 15:53 UTC, radoslawdabrowski requested changes

2021-07-29 15:53 UTC, radoslawdabrowski commented on src/main/java/javacollections/OwnList.java
> +    Integer get(int i);
Tak :) powinny być testy dla każdej z metod w interfejsie - w tym wypadku testy jednostkowe dla implementacji tego interfejsu

2021-07-29 19:01 UTC, mtszpater commented on src/main/java/javacollections/MyOwnList.java
> +    int[] array;
hermetyzacja, czemu ta lista nie jest private? Ktoś może dość łatwo (poza twoimi wystawionymi metodami) dobrać się do tej tablicy bezpośrednio i namieszać.

2021-07-29 19:01 UTC, mtszpater commented on src/test/java/javacollections/MyOwnListTest.java
> +        Assertions.assertEquals(result, array[input]);
Jakiś test na usuniecie, test na faktycznie pustą listę(jeżeli nie ma tam elementów, bo aktualnie sprawdzasz jedynie, że isEmpty zwraca false gdy dodałeś kilka elementów - a co jeżeli ktoś zmieniły implementacje tej metody i wyglądała by tak: `return false;` - twoje testy tego nie wychwycą ), test na usunięcie elementu, który nie istnieje... Te testy co wyżej napisałeś są super, ale jeszcze trochę przypadków brakuje.

2021-08-01 19:09 UTC, mtszpater approved these changes

2021-08-02 04:47 UTC, merged